network/urls.py
from django.urls import path
from . import views

app_name = 'network'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('posts', views.posts, name='posts'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('user/<str:username>', views.profile, name='profile'),
    path('following', views.following, name='following'),
    path('new_post', views.new_post, name='new_post'),
    path('follow_user/<str:username>', views.follow_unfollow_user, name='follow_user'),
    path('unfollow_user/<str:username>', views.follow_unfollow_user, name='unfollow_user'),
    path('like_post/<int:post_id>/<int:likepost>', views.like_unlike_post, name='like_post'),
    path('unlike_post/<int:post_id>/<int:likepost>', views.like_unlike_post, name='unlike_post'),
    path('like_unlike_post/<int:post_id>', views.like_unlike_post, name='like_unlike_post'),
    path('modify_post/<int:post_id>', views.modify_post, name='modify_post'),
    path('modify_reply/<int:reply_id>', views.modify_reply, name='modify_reply'),
    path('post/<int:post_id>', views.post, name='post'),
    path('post/<int:post_id>/<int:is_fetching>/<int:page_num>', views.post, name='post'),
    path('post/reply_post/<int:post_id>', views.reply_post, name='reply_post'),
    path('like_unlike_reply/<int:reply_id>', views.like_unlike_reply, name='like_unlike_reply')
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    profile_picture = models.ImageField(upload_to='network/images/profile_images/', blank=True, null=True)


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='network/images/post_images/', blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.content[:50]}"

    def num_likes(self):
        return self.likes.count()
    def num_replies(self):
        return self.replies.count()

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likess')

    def __str__(self):
        return f"{self.user.username} likes {self.post}"
    


class Follower(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    followed_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')

    def __str__(self):
        return f"{self.user.username} follows {self.followed_user.username}"

    
class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='replies')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='replies')
    parent_reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='network/images/reply_images/', blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='liked_replies', blank=True)

    def __str__(self):
        if self.parent_reply is None:
            return f"{self.user.username} replying to {self.post}"
        else:
            return f"{self.user.username} replied to {self.parent_reply}"
    def num_likes(self):
        return self.likes.count()
    def num_replies(self):
        return self.replies.count()
    def serialize_reply(self):
        user_liked = self.user.liked_replies.filter(id=self.id).exists()
        serialized_data = {
            'id': self.id,
            'user_id': self.user_id,
            'post_id': self.post_id,
            'user_username': self.user.username,
            'user_profile_picture_url': self.user.profile_picture.url if self.user.profile_picture else False,
            'parent_reply_id': self.parent_reply_id,
            'content': self.content,
            'timestamp': self.timestamp.isoformat(),
            'image_url': self.image.url if self.image else False,
            'num_likes': self.num_likes(),
            'num_replies': self.num_replies(),
            'user_liked': user_liked
        }
        return serialized_data
    
class LikeReply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE, related_name='repliess')

    def __str__(self):
        return f"{self.user.username} likes {self.reply}"

network/forms.py
# import form class from django
from django import forms
from django.core.validators import MaxLengthValidator   
# import the required models
from .models import Post, Reply, User
   
# create a ModelForm
class newPostForm(forms.ModelForm):
    image = forms.ImageField(required=False, 
                             widget=forms.FileInput(attrs={'placeholder': 'Choose Image'}),
                             )  # Add an ImageField to handle the image upload

    content = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Enter your post content', 'rows': 4, 'cols': 40}),
        validators=[MaxLengthValidator(280)]
    )
    class Meta:
        model = Post
        fields = ['content', 'image']  # Include the 'image' field in the form

class newReplyForm(forms.ModelForm):
    image = forms.ImageField(required=False, widget=forms.FileInput(attrs={'placeholder': 'Choose Image'}))  # Add an ImageField to handle the image upload
    class Meta:
        model = Reply
        fields = ['content', 'image']  # Include the 'image' field in the form

class ProfilePictureForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, widget=forms.FileInput(attrs={'placeholder': 'Choose Profile'}))
    class Meta:
        model = User
        fields = ['profile_picture']

network/views.py
import json
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from .forms import *
from .models import *
from django.shortcuts import get_object_or_404
from django.middleware import csrf
from django.utils.timesince import timesince
from .models import User


from django.core.paginator import Paginator
def index(request):
    # Get all posts ordered by timestamp
    posts = Post.objects.all().order_by('-timestamp')

    # Create a Paginator object with 10 posts per page
    paginator = Paginator(posts, 10)

    # Get the current page number from the request's GET parameters
    page_number = request.GET.get('page', 1)

    # Get the Page object for the specified page number
    page = paginator.get_page(page_number)

    context = {
        'page': page
    }
    return render(request, 'network/index.html', context)

def post(request, post_id, is_fetching=False, page_num=-1):
    # Get all posts ordered by timestamp
    post = get_object_or_404(Post, id=post_id)
    # TODO: Handle the error in case the post doesn't exist
    replies = post.replies.all().order_by('-timestamp')

    # Create a Paginator object with 10 posts per page
    paginator = Paginator(replies, 10)
    if is_fetching == 1:
        page = paginator.get_page(page_num)
        return JsonResponse({'page': [reply.serialize_reply() for reply in page], 
                             'next_page_number': page.next_page_number() if page.has_next() else -1})
    elif is_fetching == 0:
        # Get the current page number from the request's GET parameters
        page_number = request.GET.get('page', 1)

        # Get the Page object for the specified page number
        page = paginator.get_page(page_number)
        
        context = {
            'page': page,
            'post': post
        }
        return render(request, 'network/post.html', context)
    
        


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")


@login_required(login_url='network:login')
def posts(request):
    if request.method == 'POST':
        content = request.POST['content']
        post = Post(user=request.user, content=content)
        post.save()
        return redirect('network:posts')
    # TODO: Reimplement this using Pagination 
    posts = Post.objects.select_related('user').annotate(like_count=Count('likess')).order_by('-timestamp')
    return render(request, 'network/posts.html', {
        'posts': posts,
        'liked_posts': request.user.liked_posts.all()
    })


@login_required(login_url='network:login')
def profile(request, username):
    profile_user = User.objects.get(username=username)
    posts = profile_user.posts.order_by('-timestamp')
    
    # Create a Paginator object with 10 posts per page
    paginator = Paginator(posts, 10)

    # Get the current page number from the request's GET parameters
    page_number = request.GET.get('page', 1)

    # Get the Page object for the specified page number
    page = paginator.get_page(page_number)
    is_following = profile_user.followers.filter(user=request.user).exists()

    if request.method == 'POST':
        form = ProfilePictureForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
    else:
        form = ProfilePictureForm(instance=request.user)

    context = {
        'page': page,
        'posts': posts,
        'profile_user': profile_user,
        'is_following': bool(is_following),
        'form': form
    }
    return render(request, 'network/profile.html', context)
    


@login_required(login_url='network:login')
@csrf_exempt
def like_unlike_post(request, post_id, likepost=None):
    post = get_object_or_404(Post, id=post_id)
    user = request.user

    if request.method == 'POST':
        if likepost == 1:  # Like post
            like = Like.objects.filter(user=user, post=post).first()
            if like is None:
                like = Like(user=user, post=post)
                like.save()
                post.likes.add(user)
            liked = True
        elif likepost == 0:  # Unlike post
            like_queryset = Like.objects.filter(user=user, post=post)
            if like_queryset.exists():
                like_queryset.delete()
                post.likes.remove(user)
            liked = False
        else:  # Not specified
            like_queryset = Like.objects.filter(user=user, post=post)

            liked = not like_queryset.exists()

            if liked:
                like = Like(user=user, post=post)
                like.save()
                post.likes.add(user)
            else:
                like_queryset.delete()
                post.likes.remove(user)

            count = post.num_likes()
            return JsonResponse({'liked': liked, 'count': count})


@login_required(login_url='network:login')
def following(request):
    following_users = request.user.following.values_list('followed_user__id', flat=True)
    posts = Post.objects.filter(user__in=following_users).order_by('-timestamp')
    # Create a Paginator object with 10 posts per page
    paginator = Paginator(posts, 10)

    # Get the current page number from the request's GET parameters
    page_number = request.GET.get('page', 1)

    # Get the Page object for the specified page number
    page = paginator.get_page(page_number)
    context = {'page': page}
    return render(request, 'network/following.html', context)

@login_required(login_url='network:login')
def new_post(request):
    if request.method == "POST":
        form = newPostForm(request.POST, request.FILES)  # Include request.FILES in the form initialization
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, 'Post created successfully.')
            return redirect('network:index')
        else:
            messages.error(request, 'There was an error with your submission.')
    else:
        form = newPostForm()

    return render(request, "network/new_post.html", {'form': form})

@login_required(login_url='network:login')
@csrf_exempt
def modify_post(request, post_id):
    if request.method == 'POST':
        try:
            post = Post.objects.get(id=post_id)
            if request.user != post.user:
                return HttpResponseForbidden("You are not authorized to modify this post.")
            data = json.loads(request.body)
            # Retrieve the updated content from the request body
            content = data.get('content', '')

            # Update the post content
            post.content = content
            post.save()

            # Return a JSON response indicating the success
            return JsonResponse({'success': True})
        except Post.DoesNotExist:
            # Return a JSON response indicating the failure
            return JsonResponse({'success': False, 'error': 'Post not found'})
    
    # Return a JSON response indicating the incorrect HTTP method
    return JsonResponse({'success': False, 'error': 'Invalid request method'})

@login_required(login_url='network:login')
@csrf_exempt
def follow_unfollow_user(request, username):
    target_user = User.objects.get(username=username)
    if request.method == 'POST':
        user = request.user

        # Definitely not the best way to go about it but anyways
        follow_queryset = Follower.objects.filter(user=user, followed_user=target_user)
        isfollowing = not follow_queryset.exists()

        if isfollowing:
            follow = Follower(user=user, followed_user=target_user)
            follow.save()
            # user.following.add(target_user) No need for the Follower model

        else:
            follow = follow_queryset.delete()
            # user.following.remove(target_user) No need for the Follower model
            
        
            

        num_followers = target_user.followers.count()
        num_following = target_user.following.count()

network/templates/network/following.html
<!-- network: following.html-->
{% extends 'network/layout.html' %}

{% block body %}
    <h1>Following</h1>

    <!-- Posts List -->
    <ul>
        {% for post in page%}
            {% include 'network/post_display.html' with post=post user=user %}
        {% endfor %}
    </ul>
    <!-- Render pagination links -->
    <div class="pagination">
        <span class="step-links">
        <span class="current-page">{{ page.number }}</span>
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}"><button class="btn btn-primary np">previous</button></a>
        {% endif %}
        
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}"><button class="btn btn-primary np">next</button></a>
        {% endif %}
        </span>
    </div>
{% endblock %}

network/templates/network/index.html
<!-- network: index.html -->
{% extends "network/layout.html" %}

{% block body %}
    {% if user.is_authenticated %}
    <a href="{% url 'network:new_post' %}"><input class="btn btn-primary np" type="submit" value="New Post"></button></a>
    {% endif %}
    {% for post in page%}
        {% include 'network/post_display.html' with post=post user=user %}
    {% endfor %}
    <!-- Render pagination links -->
    <div class="pagination">
        <span class="step-links">
        <span class="current-page">{{ page.number }}</span>
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}"><button class="btn btn-primary np">previous</button></a>
        {% endif %}
        
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}"><button class="btn btn-primary np">next</button></a>
        {% endif %}
        </span>
    </div>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
        <link href="{% static 'network/styles.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'network:index' %}">Tikter</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'network:profile' username=user.username %}" class="current-user" data-current-userid="{{user.id}}"><strong>{{ user.username }}</strong></a>
                    </li>
                   
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:following' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
          
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
        <script src="{% static 'network/js/follow.js' %}"></script>
        <script src="{% static 'network/js/like.js' %}"></script>
        <script src="{% static 'network/js/edit.js' %}"></script>
        <script src="{% static 'network/js/postClick.js' %}"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>
            {% block extrajs %}
            {% endblock %}
    </body>
    
</html>

network/templates/network/login.html
<!-- network:login.html -->
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

network/templates/network/new_post.html
<!--New Post Html-->
{% extends 'network/layout.html' %}
{% load static %}
{% block body %}
<!-- if the user is authenticated, then they can post-->
    {% if user.is_authenticated %}
    <form action="{% url 'network:new_post'%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>New Post</h3>
        <div class="post-form">
            <span>
                <div>{{form.content}}</div>
            </span>
            
                <div class="container-progress np-progress" id="np-progress">
                    <div class="circular-progress np-progress">
                      <div class="value-container-progress np-progress"></div>
                    </div>
                  </div> 
            
            <div>{{form.image}}</div>
            <div>
                <input class="btn btn-primary post-btn" type="submit" value="Post">
            </div>
        </div>
        
        
    </form>
    {% endif %}
{% endblock %}

{% block extrajs %}
    <script src="{% static 'network/js/newPost.js' %}"></script>
{% endblock %}

network/templates/network/post.html
<!-- network: post.html -->
{% extends "network/layout.html" %}
    {% load static %}
    {% block title%} Post {% endblock %}
    
    {% block body %}
        {% include 'network/post_display.html' with post=post user=user %}
        {% if user.is_authenticated %}
            <div class="reply-section">
                <div class="reply-area">{% csrf_token %}
                    <span><div class="reply-header"></div><textarea class="textarea-reply" placeholder="tikt your reply..."></textarea>
                    <div class="container-progress">
                        <div class="circular-progress">
                        <div class="value-container-progress"></div>
                        </div>
                    </div> 
                    </span>   
                    <span><button class="btn btn-primary reply-btn" data-post-id="{{ post.id}}" data-post-username="{{post.user.username}}">Reply</button></span>
                </div>
                
            </div>
            <div class="user-reply"></div>
        {% endif %}
        <div class="replies">
        {% for reply in page%}
            {% include 'network/reply_display.html' with reply=reply user=user %}    
        {% endfor %}
        </div>
        <!-- Render pagination links -->
        <div class="pagination" style="display: none;"><!--Set display to none for infinite scroll-->
            <span class="step-links">
            <span class="current-page btn">{{ page.number }}</span>
            {% if page.has_previous %}
                <a href="?page={{ page.previous_page_number }}"><button class="btn btn-primary np">previous</button></a>
            {% endif %}
            
            {% if page.has_next %}
                <span class="page-number" data-page-number="{{ page.next_page_number }}"></span>
                <a href="?page={{ page.next_page_number }}"><button class="btn btn-primary np">next</button></a>\
            {% else %}
                <span class="page-number" data-page-number="-1"></span>    
            {% endif %}
            </span>
        </div>

        
    {% endblock %}

    
    {% block extrajs %}
    <script src="{% static 'network/js/reply.js' %}"></script>
    <script src="{% static 'network/js/likeReply.js' %}"></script>
    <script src="{% static 'network/js/editReply.js' %}"></script>
    <script src="{% static 'network/js/infiniteScroll.js' %}"></script>
    {% endblock %}

network/templates/network/post_display.html
<!--post_display.html-->
<li class="post-li" data-post-id="{{ post.id }}">
    <div class="post-section">
        <a class="user-link il" href="{% url 'network:profile' username=post.user.username%}">
          <span class="profile-image-container">
            {% if post.user.profile_picture %}
                <img src="{{ post.user.profile_picture.url }}" alt="Profile Image" class="profile-image">
            {% endif %}
          </span>
         
          <strong>{{ post.user.username }}</strong>
       </a>
    <p class="p-content">{{ post.content }}</p>
    <div class="image-container">
        {% if post.image %}
            <img src="{{ post.image.url }}" alt="Post Image" class="post-image">
        {% endif %}
    </div>
    {% if user.is_authenticated %}
        <p>
            <div>
            <span class="like-count">{{ post.num_likes }}</span>    
            <span class="like-button il" data-post-id="{{ post.id }}" >
                {% if post in user.liked_posts.all %}
                    <i class="heart-icon fas fa-heart liked"></i>
                {% else %}
                    <i class="heart-icon far fa-heart"></i>
                {% endif %}
                
            </span>
            
            </div>
            <span class="post-reply-count">{{ post.num_replies }}</span>
            <a href="#" class="reply-icon">
                <i class="fa fa-reply" href="{% url 'network:post' post_id=post.id %}"></i> Reply
            </a>

        </p>
        
    {% else %}
        <p><i class="far fa-heart"></i> <span class="like-count">{{ post.num_likes }} </span></p>
    {% endif %}
    <p class="timestamp">{{ post.timestamp|timesince }} ago</p>
    </div>
    {% if user == post.user %}
    <div class="edit-section il">{% csrf_token %}
        <div><button class="btn btn-primary edit-btn po" data-post-id="{{ post.id}}">Edit</button></div>
        <div><textarea class="textarea-edit" data-value="{{ post.content }}"></textarea></div>    
    </div>
    {% endif %}   
</li>
    

network/templates/network/register.html
<!--network: register.html-->
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

{% endblock %}

network/templates/network/reply_display.html
<!--network: reply_display.html-->
<li class="reply-li" data-reply-id="{{ reply.id }}">
    <div class="reply-section">
    <a class="user-link" href="{% url 'network:profile' username=reply.user.username%}">
        <span class="profile-image-container">
            {% if reply.user.profile_picture %}
                <img src="{{ reply.user.profile_picture.url }}" alt="Profile Image" class="profile-image">
            {% endif %}
        </span>
        <strong>{{ reply.user.username }}</strong>
    </a>
    <p class="r-content">{{ reply.content }}</p>
    <div class="image-container">
        {% if reply.image %}
            <img src="{{ reply.image.url }}" alt="Reply Image" class="post-image">
        {% endif %}
    </div>
    {% if user.is_authenticated %}
        <p>
            
            <span class="rlike-count">{{ reply.num_likes }}</span>
            <span class="rlike-button" data-reply-id="{{ reply.id }}" >
                {% if reply in user.liked_replies.all %}
                    <i class="heart-icon fas fa-heart liked"></i>
                {% else %}
                    <i class="heart-icon far fa-heart"></i>
                {% endif %}
            </span>
            
            <span class="reply-reply-count">{{ reply.num_replies }}</span>
            <a href="#" class="reply-icon">
                <i class="fa fa-reply"></i> Reply
            </a>

        </p>
        
    {% else %}
        <p><i class="far fa-heart"></i> <span class="rlike-count">{{ reply.num_likes }} </span></p>
    {% endif %}
    <p class="timestamp">{{ reply.timestamp|timesince }} ago</p>
    </div>
    {% if user == reply.user %}
    <div class="edit-section">{% csrf_token %}
        <div><button class="btn btn-primary edit-btn" data-reply-id="{{ reply.id}}">Edit</button></div>
        <div><textarea class="textarea-edit" data-value="{{ reply.content }}"></textarea></div>    
    </div>
    {% endif %}   
</li>
    